<a href="https://colab.research.google.com/github/Logeshwari-2001/Anomaly/blob/main/anomaly_train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn
import imblearn
import sys

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Settings
pd.set_option('display.max_columns', None)
np.set_printoptions(threshold=sys.maxsize)
np.set_printoptions(precision=3)
sns.set(style="darkgrid")
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

print("pandas : {0}".format(pd.__version__))
print("numpy : {0}".format(np.__version__))
print("matplotlib : {0}".format(matplotlib.__version__))
print("seaborn : {0}".format(sns.__version__))
print("sklearn : {0}".format(sklearn.__version__))
print("imblearn : {0}".format(imblearn.__version__))

pandas : 1.4.4
numpy : 1.22.4
matplotlib : 3.7.1
seaborn : 0.12.2
sklearn : 1.2.2
imblearn : 0.10.1


In [3]:
datacols = ["duration","protocol_type","service","flag","src_bytes",
    "dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins",
    "logged_in","num_compromised","root_shell","su_attempted","num_root",
    "num_file_creations","num_shells","num_access_files","num_outbound_cmds",
    "is_host_login","is_guest_login","count","srv_count","serror_rate",
    "srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
    "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
    "dst_host_rerror_rate","dst_host_srv_rerror_rate","attack", "last_flag"]

# Load NSL_KDD train dataset
train = pd.read_table("/content/KDDTrain.txt", sep=",", names=datacols) # change path to where the dataset is located.
train = train.iloc[:,:-1] # removes an unwanted extra field

In [4]:
print(train.head(4))

print("Training data has {} rows & {} columns".format(train.shape[0],train.shape[1]))

   duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0         0           tcp  ftp_data   SF        491          0     0   
1         0           udp     other   SF        146          0     0   
2         0           tcp   private   S0          0          0     0   
3         0           tcp      http   SF        232       8153     0   

   wrong_fragment  urgent  hot  num_failed_logins  logged_in  num_compromised  \
0               0       0    0                  0          0                0   
1               0       0    0                  0          0                0   
2               0       0    0                  0          0                0   
3               0       0    0                  0          1                0   

   root_shell  su_attempted  num_root  num_file_creations  num_shells  \
0           0             0         0                   0           0   
1           0             0         0                   0           0   
2           0 

In [5]:
mapping = {'ipsweep': 'Probe','satan': 'Probe','nmap': 'Probe','portsweep': 'Probe','saint': 'Probe','mscan': 'Probe',
        'teardrop': 'DoS','pod': 'DoS','land': 'DoS','back': 'DoS','neptune': 'DoS','smurf': 'DoS','mailbomb': 'DoS',
        'udpstorm': 'DoS','apache2': 'DoS','processtable': 'DoS',
        'perl': 'U2R','loadmodule': 'U2R','rootkit': 'U2R','buffer_overflow': 'U2R','xterm': 'U2R','ps': 'U2R',
        'sqlattack': 'U2R','httptunnel': 'U2R',
        'ftp_write': 'R2L','phf': 'R2L','guess_passwd': 'R2L','warezmaster': 'R2L','warezclient': 'R2L','imap': 'R2L',
        'spy': 'R2L','multihop': 'R2L','named': 'R2L','snmpguess': 'R2L','worm': 'R2L','snmpgetattack': 'R2L',
        'xsnoop': 'R2L','xlock': 'R2L','sendmail': 'R2L',
        'normal': 'Normal'
        }

In [6]:
train['attack_class'] = train['attack'].apply(lambda v: mapping[v])

In [7]:
train.drop(['attack'], axis=1, inplace=True)

In [8]:
train.head(3)

duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0         0           tcp  ftp_data   SF        491          0     0   
1         0           udp     other   SF        146          0     0   
2         0           tcp   private   S0          0          0     0   

   wrong_fragment  urgent  hot  num_failed_logins  logged_in  num_compromised  \
0               0       0    0                  0          0                0   
1               0       0    0                  0          0                0   
2               0       0    0                  0          0                0   

   root_shell  su_attempted  num_root  num_file_creations  num_shells  \
0           0             0         0                   0           0   
1           0             0         0                   0           0   
2           0             0         0                   0           0   

   num_access_files  num_outbound_cmds  is_host_login  is_guest_login  count  \
0                 0                  0              0               0      2   
1                 0                  0              0               0     13   
2                 0                  0              0               0    123   

   srv_count  serror_rate  srv_serror_rate  rerror_rate  srv_rerror_rate  \
0          2          0.0              0.0          0.0              0.0   
1          1          0.0              0.0          0.0              0.0   
2          6          1.0              1.0          0.0              0.0   

   same_srv_rate  diff_srv_rate  srv_diff_host_rate  dst_host_count  \
0           1.00           0.00                 0.0             150   
1           0.08           0.15                 0.0             255   
2           0.05           0.07                 0.0             255   

   dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                  25                    0.17                    0.03   
1                   1                    0.00                    0.60   
2                  26                    0.10                    0.05   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.17                          0.0   
1                         0.88                          0.0   
2                         0.00                          0.0   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                  0.05   
1                   0.0                       0.0                  0.00   
2                   1.0                       1.0                  0.00   

   dst_host_srv_rerror_rate attack_class  
0                       0.0       Normal  
1                       0.0       Normal  
2                       0.0          DoS

In [9]:
print(train['num_outbound_cmds'].value_counts())

0    125973
Name: num_outbound_cmds, dtype: int64


In [10]:
train.drop(['num_outbound_cmds'], axis=1, inplace=True)

In [11]:
attack_class_freq_train = train[['attack_class']].apply(lambda x: x.value_counts())
#attack_class_freq_test = test[['attack_class']].apply(lambda x: x.value_counts())
attack_class_freq_train['frequency_percent_train'] = round((100 * attack_class_freq_train / attack_class_freq_train.sum()),2)

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# extract numerical attributes and scale it to have zero mean and unit variance  
cols = train.select_dtypes(include=['float64','int64']).columns
sc_train = scaler.fit_transform(train.select_dtypes(include=['float64','int64']))
#sc_test = scaler.fit_transform(test.select_dtypes(include=['float64','int64']))

# turn the result back to a dataframe
sc_traindf = pd.DataFrame(sc_train, columns = cols)
#sc_testdf = pd.DataFrame(sc_test, columns = cols)

In [13]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

# extract categorical attributes from both training and test sets 
cattrain = train.select_dtypes(include=['object']).copy()
#cattest = test.select_dtypes(include=['object']).copy()

# encode the categorical attributes
traincat = cattrain.apply(encoder.fit_transform)
#testcat = cattest.apply(encoder.fit_transform)

# separate target column from encoded data 
enctrain = traincat.drop(['attack_class'], axis=1)
cat_Ytrain = traincat[['attack_class']].copy()

In [14]:
train_x = pd.concat([sc_traindf,enctrain],axis=1)
train_y = train['attack_class']
train_x.shape

(125973, 40)

In [15]:
train_x

duration  src_bytes  dst_bytes      land  wrong_fragment    urgent  \
0      -0.110249  -0.007679  -0.004919 -0.014089       -0.089486 -0.007736   
1      -0.110249  -0.007737  -0.004919 -0.014089       -0.089486 -0.007736   
2      -0.110249  -0.007762  -0.004919 -0.014089       -0.089486 -0.007736   
3      -0.110249  -0.007723  -0.002891 -0.014089       -0.089486 -0.007736   
4      -0.110249  -0.007728  -0.004814 -0.014089       -0.089486 -0.007736   
...          ...        ...        ...       ...             ...       ...   
125968 -0.110249  -0.007762  -0.004919 -0.014089       -0.089486 -0.007736   
125969 -0.107178  -0.007744  -0.004883 -0.014089       -0.089486 -0.007736   
125970 -0.110249  -0.007382  -0.004823 -0.014089       -0.089486 -0.007736   
125971 -0.110249  -0.007762  -0.004919 -0.014089       -0.089486 -0.007736   
125972 -0.110249  -0.007737  -0.004919 -0.014089       -0.089486 -0.007736   

             hot  num_failed_logins  logged_in  num_compromised  root_shell  \
0      -0.095076          -0.027023  -0.809262        -0.011664   -0.036652   
1      -0.095076          -0.027023  -0.809262        -0.011664   -0.036652   
2      -0.095076          -0.027023  -0.809262        -0.011664   -0.036652   
3      -0.095076          -0.027023   1.235694        -0.011664   -0.036652   
4      -0.095076          -0.027023   1.235694        -0.011664   -0.036652   
...          ...                ...        ...              ...         ...   
125968 -0.095076          -0.027023  -0.809262        -0.011664   -0.036652   
125969 -0.095076          -0.027023  -0.809262        -0.011664   -0.036652   
125970 -0.095076          -0.027023   1.235694        -0.011664   -0.036652   
125971 -0.095076          -0.027023  -0.809262        -0.011664   -0.036652   
125972 -0.095076          -0.027023   1.235694        -0.011664   -0.036652   

        su_attempted  num_root  num_file_creations  num_shells  \
0          -0.024437 -0.012385            -0.02618    -0.01861   
1          -0.024437 -0.012385            -0.02618    -0.01861   
2          -0.024437 -0.012385            -0.02618    -0.01861   
3          -0.024437 -0.012385            -0.02618    -0.01861   
4          -0.024437 -0.012385            -0.02618    -0.01861   
...              ...       ...                 ...         ...   
125968     -0.024437 -0.012385            -0.02618    -0.01861   
125969     -0.024437 -0.012385            -0.02618    -0.01861   
125970     -0.024437 -0.012385            -0.02618    -0.01861   
125971     -0.024437 -0.012385            -0.02618    -0.01861   
125972     -0.024437 -0.012385            -0.02618    -0.01861   

        num_access_files  is_host_login  is_guest_login     count  srv_count  \
0              -0.041221      -0.002817       -0.097531 -0.717045  -0.354343   
1              -0.041221      -0.002817       -0.097531 -0.620982  -0.368110   
2              -0.041221      -0.002817       -0.097531  0.339648  -0.299273   
3              -0.041221      -0.002817       -0.097531 -0.690846  -0.313041   
4              -0.041221      -0.002817       -0.097531 -0.472521   0.058678   
...                  ...            ...             ...       ...        ...   
125968         -0.041221      -0.002817       -0.097531  0.872361  -0.037694   
125969         -0.041221      -0.002817       -0.097531 -0.717045  -0.354343   
125970         -0.041221      -0.002817       -0.097531 -0.725778  -0.368110   
125971         -0.041221      -0.002817       -0.097531  0.523041  -0.271739   
125972         -0.041221      -0.002817       -0.097531 -0.725778  -0.368110   

        serror_rate  srv_serror_rate  rerror_rate  srv_rerror_rate  \
0         -0.637209        -0.631929    -0.374362        -0.374432   
1         -0.637209        -0.631929    -0.374362        -0.374432   
2          1.602664         1.605104    -0.374362        -0.374432   
3         -0.189235        -0.184522    -0.374362        -0.374432   
4         -0.63720

In [17]:
train_y=train.attack_class
train_y

0         Normal
1         Normal
2            DoS
3         Normal
4         Normal
           ...  
125968       DoS
125969    Normal
125970    Normal
125971       DoS
125972    Normal
Name: attack_class, Length: 125973, dtype: object

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train_x,train_y, test_size = 0.2, random_state = 0)
X_train.shape, X_test.shape

((100778, 40), (25195, 40))

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
sel = RFE(RandomForestClassifier(n_estimators=100, random_state=0, n_jobs=-1), n_features_to_select = 15)
sel.fit(X_train, y_train)

RFE(estimator=RandomForestClassifier(n_jobs=-1, random_state=0),
    n_features_to_select=15)

In [22]:
sel.get_support()
features = X_train.columns[sel.get_support()]
features

Index(['src_bytes', 'dst_bytes', 'count', 'srv_count', 'same_srv_rate',
       'diff_srv_rate', 'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'protocol_type',
       'service', 'flag'],
      dtype='object')

In [23]:
len(features)

15

In [24]:
X_train_rfe = sel.transform(X_train)
X_test_rfe = sel.transform(X_test)

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 

# instantiate the model (using the default parameters)
#logreg = LogisticRegression(random_state=16)
classifier = SVC(random_state=0)
classifier.fit(X_train_rfe, y_train)
logreg = LogisticRegression(n_jobs=-1,random_state=0)
# fit the model with data
logreg.fit(X_train_rfe, y_train)

LogisticRegression(n_jobs=-1, random_state=0)

In [28]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
models = []
models.append(('SVM Classifier', classifier))
models.append(('LogisticRegression', logreg))

for i, v in models:
    #scores = cross_val_score(v, X_train, Y_train, cv=10)
    accuracy = metrics.accuracy_score(y_train, v.predict(X_train_rfe))
    confusion_matrix = metrics.confusion_matrix(y_train, v.predict(X_train_rfe))
    classification = metrics.classification_report(y_train, v.predict(X_train_rfe))
    print()
    print('============================== {} Model Evaluation =============================='.format(i))
    print()
    #print ("Cross Validation Mean Score:" "\n", scores.mean())
    #print()
    print ("Model Accuracy:" "\n", accuracy)
    print()
    
    print("Confusion matrix:" "\n", confusion_matrix)
    print()
    print("Classification report:" "\n", classification) 
    print()


============================== SVM Classifier Model Evaluation ==============================

Model Accuracy:
 0.955684772470182

Confusion matrix:
 [[34879  1552   330     0     0]
 [  213 53285   388     0     0]
 [  193   973  8148     0     0]
 [   36   742     2     0     0]
 [    1    36     0     0     0]]

Classification report:
               precision    recall  f1-score   support

         DoS       0.99      0.95      0.97     36761
      Normal       0.94      0.99      0.96     53886
       Probe       0.92      0.87      0.90      9314
         R2L       0.00      0.00      0.00       780
         U2R       0.00      0.00      0.00        37

    accuracy                           0.96    100778
   macro avg       0.57      0.56      0.57    100778
weighted avg       0.95      0.96      0.95    100778



============================== LogisticRegression Model Evaluation ==============================

Model Accuracy:
 0.9292802000436603

Confusion matrix:
 [[34529  212

In [31]:
for i, v in models:
    accuracy = metrics.accuracy_score(y_test, v.predict(X_test_rfe))
    confusion_matrix = metrics.confusion_matrix(y_test, v.predict(X_test_rfe))
    classification = metrics.classification_report(y_test, v.predict(X_test_rfe))
    print()
    print('============================== {} Model Test Results =============================='.format(i))
    print()
    print ("Model Accuracy:" "\n", accuracy)
    print()
    print("Confusion matrix:" "\n", confusion_matrix)
    print()
    print("Classification report:" "\n", classification) 
    print()


============================== SVM Classifier Model Test Results ==============================

Model Accuracy:
 0.9547132367533241

Confusion matrix:
 [[ 8718   375    73     0     0]
 [   53 13310    94     0     0]
 [   56   260  2026     0     0]
 [   11   204     0     0     0]
 [    0    15     0     0     0]]

Classification report:
               precision    recall  f1-score   support

         DoS       0.99      0.95      0.97      9166
      Normal       0.94      0.99      0.96     13457
       Probe       0.92      0.87      0.89      2342
         R2L       0.00      0.00      0.00       215
         U2R       0.00      0.00      0.00        15

    accuracy                           0.95     25195
   macro avg       0.57      0.56      0.57     25195
weighted avg       0.95      0.95      0.95     25195



============================== LogisticRegression Model Test Results ==============================

Model Accuracy:
 0.9295098233776543

Confusion matrix:
 [[ 8641